---
- name: Ensure that variables are present
  assert:
    that: 
      - host.name is defined 
      - host.interface.public.ip is defined 
      - host.domain is defined 
      - host.ntpserver is defined 
      - host.nameserver is defined 
