---
- name: Ensure that variables are present
  assert:
    that: 
      - item.name is defined 
      - item.ip is defined 
      - item.domain is defined 
      - item.ntpserver is defined 
      - item.nameserver is defined 
  with_dict: "{{ host }}"
