---
# ######################################################
# This role will create LVM Volumes for Hana if defined
# ######################################################

- local_action: shell ping -q -c 1 -W 1 {{ hostname }}
  register: ping_result
  ignore_errors: yes

- include: ./pxeconfig.yml
  when: ('100% packet loss' in ping_result.stdout)

