---
# ######################################################
# This role will create LVM Volumes for Hana if defined
# ######################################################

- include_tasks: ./assert.yml

- debug:
   msg: "######################     Stage 1 -  Creating PXE config   ######################"
- name: " Stage 1 -  Ping Test"
  local_action: "shell ping -q -c 1 -W 1 {{ pxeserver.host_to_install }}"
  changed_when: false
  ignore_errors: yes
  register: ping_result
   
- include_tasks: ./pxeconfig.yml
  when: ('100% packet loss' in ping_result.stdout)

- debug:
    msg: " Skipping PXE boot - System IP {{ pxeserver.host_to_install }} is reachable"
  when: ('100% packet loss' in ping_result.stdout)
