---
##########################################################################
# Prepareing autoyast / kickstart files and pxe template for installation
##########################################################################

- name: " Stage 1 -  Enrole autoyast file to pxeserver"
  template:
    src: autoyast.xml.j2
    dest: "/var/lib/tftpboot/img/autoyast/{{ host.name }}.xml"
  delegate_to: "{{ pxeserver.ip }}"

- name: " Stage 1 -  Adding host to DHCP (group SLES12SP3)"
  blockinfile:
    block: |
      host {{ host.name }}.{{ host.domain }} {
      ddns-hostname "{{ host.name }}";
      option host-name "{{ host.name }}.{{ host.domain }}";
      hardware ethernet {{ host.interface.public.mac }};
      }
    insertafter: "group { # First default group"
    path: /etc/dhcp/dhcpd.conf
  delegate_to: "{{ pxeserver.ip }}"

- name: " Stage 1 -  Copy PXE template to pxeserver"
  template:
    src: pxefile-host.j2
    dest: "/var/lib/tftpboot/pxelinux.cfg/01-{{ host.interface.public.mac |regex_replace(':','-')|lower }}"
  delegate_to: "{{ pxeserver.ip }}"

##########################################################################
# Waiting until system  installation is triggered and system is availanle
##########################################################################

- name: " Stage 1 -  Waiting for autoyastfile to be loaded by installer - Please start the System NOW!"
  block:
    - name: " Stage 1 -  Creating temp logfile"
      tempfile:
        state: file
      register: tempfile
    - name: " Stage 1 -  Redirect of httpd log to temp logfile"
      shell: tail -n 0 -f /var/log/httpd/access_log > {{ tempfile.path }}
      async: 500
      poll: 0
    - debug:
        msg: "#####################  ->    Please restart the System NOW!    <-  #####################"
    - name: " Stage 1 -  Waiting for autoyastfile to be loaded by installer."
      wait_for:
        path: "{{ tempfile.path }}"
        search_regex: ".*/autoyast/{{ host.name }}.xml"
    - name: " Stage 1 -  Deleting temp logfile"
      file:
        path: "{{ tempfile.path }}"
        state: absent
    - name: " Stage 1 -  remove PXE template"
      file:
        state: absent
        path: "/var/lib/tftpboot/pxelinux.cfg/01-{{ host.interface.public.mac |regex_replace(':','-')|lower }}"
  delegate_to: "{{ pxeserver.ip }}"

- name: " Stage 1 -  Wait for installation to complete"
  wait_for_connection:
    connect_timeout: 20
    sleep: 30
    delay: 180
    timeout: 2700
  delegate_to: "{{ host.interface.public.ip }}"
