---
# tasks file for saphana-pxe-autoyast-deploy

- name: " Stage 1 -  Enrole autoyast file to pxeserver"
  template:
    src: autoyast.xml.j2
    dest: "/var/lib/tftpboot/img/autoyast/{{ item.key }}.xml"
  with_dict: "{{ host }}"

- name: " Stage 1 -  Adding host to DHCP (group SLES12SP3)"
  blockinfile:
    block: |
      host {{ item.key }}.{{ item.value.domain }} {
      ddns-hostname "{{ item.key }}";
      option host-name "{{ item.key }}.{{ item.value.domain }}";
      hardware ethernet {{ item.value.interface.eth0.mac }};
      }
    insertafter: "group { # SLES12SP3"
    path: /etc/dhcp/dhcpd.conf
  with_dict: "{{ host }}"

- name: " Stage 1 -  Copy PXE template to pxeserver"
  template:
    src: pxefile-host.j2
    dest: "/var/lib/tftpboot/pxelinux.cfg/01-{{ item.value.interface.eth0.mac |regex_replace(':','-')|lower }}"
  with_dict: "{{ host }}"

######################################################################
# Waiting until system  installation is triggered
######################################################################

- name: " Stage 1 -  Waiting for autoyastfile to be loaded by installer - Please start the System NOW!"
  block:
    - name: " Stage 1 -  Creating temp logfile"
      tempfile:
        state: file
      register: tempfile
    - name: " Stage 1 -  Redirect of httpd log to temp logfile"
      shell: tail -n 0 -f /var/log/httpd/access_log > {{ tempfile.path }}
      async: 500
      poll: 0
    - name: " Stage 1 -  Waiting for autoyastfile to be loaded by installer - Please start the System NOW!"
      wait_for:
        path: "{{ tempfile.path }}"
        search_regex: ".*/autoyast/{{ item.key }}.xml"
      with_dict: "{{ host }}"
    - name: " Stage 1 -  Deleting temp logfile"
      file:
        path: "{{ tempfile.path }}"
        state: absent
    - name: " Stage 1 -  remove PXE template"
      file:
        state: absent
        path: "/var/lib/tftpboot/pxelinux.cfg/01-{{ item.value.interface.eth0.mac |regex_replace(':','-')|lower }}"
      with_dict: "{{ host }}"

- name: " Stage 1 -  Wait for installation to complete"
  wait_for_connection:
    connect_timeout: 20
    sleep: 30
    delay: 180
    timeout: 2700
  delegate_to: "{{ item.key }}.{{ item.value.domain }}"
  with_dict: "{{ host }}"
