---

- name: " Stage 4.3 -   Create backup-directory"
  file:
    path: "{{ volumes.hana_backup.mountpoint }}/{{  item }}"
    state: directory
    owner: "{{ instances.value.sid|lower }}adm" 
  with_items:
    - data
    - log

- name: " Stage 4.3 -   Change default Destination for Backups of the Backup Catalog"
  lininfile:
    path:/hana/shared/{{  instance.value.sid|upper  }}/global/hdb/custom/config/global.ini
    regexp:"{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: "{{ item.insertafter }}"
  with_items:
    - { regexp: '^[persistence]', line: '[persistence]', insertafter: ''}
    - { regexp: '^basepath_catalogbackup', line: 'basepath_catalogbackup={{ volumes.hana_backup.mountpoint }}/log', insertafter: '[persistence]'}
    - { regexp: '^basepath_databackup', line: 'basepath_databackup={{ volumes.hana_backup.mountpoint }}/data', insertafter: '[persistence]'}
    - { regexp: '^basepath_logbackup', line: 'basepath_logbackup={{ volumes.hana_backup.mountpoint }}/log', insertafter: '[persistence]'}
  register: backup
  when: volumes.hana.backup is defined

- name: " Stage 4.3 -   Copy Backup script to host"
  templates:
    src: create_backup.sh.j2
    dest: /usr/local/bin/create_backup.sh
    mode: 755
  with_dict: " {{ instances }}"
  when: backup.changed and volumes.hana.backup is defined

- name: " Stage 4.3 -   Create Backup"
  shell: ./create_backup.sh
    chdir: "/usr/local/bin/"
  when: backup.changed and volumes.hana.backup is defined
