---
##############################
# Installation of SAP HANA Host Agent
##############################


# Installation of SAP HANA Host Agent
# Need this for ScaleOut Enviornments
# Did not work with ssh under SLES12, RHEL6, RHEL7
# https://access.redhat.com/solutions/1370033

- name: " Stage 4.1 -   Create sapsys group"
  group: 
    name: sapsys 
    gid: "{{ saphostagent.sapadm_useri_id }}"

- name: " Stage 4.1 -   Create sapadm user"
  user:
    name: sapadm
    uid: "{{ saphostagent.sapadm_useri_id }}"
    group: sapsys
    password: "{{ saphostagent.sapadm_password | password_hash('sha512') }}"
  changed_when: false

- name: " Stage 4.1 -   Installation File SAP HANA Host Agent"
  template:
    src: hostagent_install/install_saphostagent.sh.j2
    dest: /usr/local/bin/install_saphostagent.sh
    mode: 0755

- name: " Stage 4.1 -   Install SAP HANA Host Agent"
  shell: /usr/local/bin/install_saphostagent.sh
  args:
  changed_when: false

# Setup sap hana Hostagent SSL
# http://help.sap.com/saphelp_nw73ehp1/helpdata/en/8d/12f7b9244b44219bd14d619d3a2123/content.htm
# Based on RHEL Documentation https://access.redhat.com/solutions/1370033
- name: " Stage 4.1 -   Create directory for SAP HANA Hostagent SSL Configuration"
  file:
    path: /usr/sap/hostctrl/exe/sec
    state: directory
    mode: 0755
    owner: sapadm
    group: sapsys

- name: " Stage 4.1 -   Deployfile for HANA Host Agent SSL Configuration"
  template: 
    src: hostagent_install/install_sslforsaphostagent.sh.j2
    dest: /usr/local/bin/install_sslforsaphostagent.sh
    mode: 0755

- name: " Stage 4.1 -   Ensure SSL is configured for saphostagent"
  shell: /usr/local/bin/install_sslforsaphostagent.sh
  notify: "Restart HostAgent"
  args:
  changed_when: false

- name: " Stage 4.1 -   Change user for SAPSSLS.pse file for SAP Host Agent"
  file:
    path: /usr/sap/hostctrl/exe/sec/SAPSSLS.pse
    state: file
    owner: sapadm
    group: sapsys
