---
# ######################################################
# This role will create LVM Volumes for Hana if defined
# ######################################################

- include_tasks: ./assert.yml

- debug:
   msg: "######################     Stage 4 -  Deploy SAP Hana DB   ######################"


- include_tasks: ./hostagent.yml
- include_tasks: ./deployment.yml
  tags:
    - hana-install

