---
- name: " Stage 2.2 -   Check / set hostname"
  hostname:
    name: "{{ item.key }}"
  with_dict: "{{ host }}"

- name: " Stage 2.2 -   Setting correct hostname in /etc/hosts"
  lineinfile:
    path: /etc/hosts
    regexp: "{{ item.key }}"
    line: "{{ item.value.interface.eth0.ip }}  {{ item.key }}.{{ item.value.domain }}  {{ item.key }}"
  with_dict: "{{ host }}"

- name: " Stage 2.2 -   Setting DNS config"
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver {{ item }}"
  with_items: "{{ nameserver }}"

- name: " Stage 2.2 -  Remove DVD repo"
  zypper_repository:
    state: absent
    name: 'SLE-12-SP3-SAP-12.3-0'

########################
# Fix me Suse registration
##########################
#- name: check regitered status
#  shell: SUSEConnect -s |awk -F: '{print  $5}'| cut -d \" -f2
#  register: regstatus
#  when: not ( (registration.regcode is undefined) or (registration.regcode is undefined is none) or (registration.regcode is undefined | trim == '') or (registration.email is undefined) or (registration.email is undefined is none) or (registration.email is undefined | trim == '') )

- name: " Stage 2.2 -   Register system"
  shell: "SUSEConnect -r {{ item.value.registration.regcode }} -e {{ item.value.registration.email }}"
  with_dict: "{{ host }}"
 # when: regstatus.value != "Not Registered"

- name: " Stage 2.2 -   Refresh all repos"
  zypper_repository:
    repo: '*'
    runrefresh: yes

- name: " Stage 2.2 -  Install packages"
  zypper:
    state: latest
    name: "{{ packages }}"

- name: " Stage 2.2 -   Setting NTP server"
  block:
   - lineinfile:
       path: /etc/ntp.conf
       line: "server {{ ntpserver.ip }}"
     notify: restart ntp
   - timezone:
       name: "{{ ntpserver.timezone }}"
  when: not( (ntpserver is undefined) or (ntpserver is none) or (ntpserver | trim == '') )


### TODO: Configure Firewall according to instance number instead of disabling
- name: " Stage 2.2 -  Configure Services"
  service: 
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    enabled: "{{ item.enabled }}"
  with_items:
    - { name: 'SuSEfirewall2', state: 'stopped', enabled: 'no' }
    - { name: 'kdump', state: 'stopped', enabled: 'no' }
    - { name: 'uuidd', state: 'started', enabled: 'yes' }
    - { name: 'tuned', state: 'started', enabled: 'yes' }
    - { name: 'ntpd', state: 'started', enabled: 'yes' }
