---
- name: Ensure that variables are present
  assert:
    that: 
      - host.name is defined 
      - host.domain is defined
      - host.interface.public.mac is defined
      - host.ntpserver is defined
      - host.timezone is defined
      - host.saptune_solution is defined
      - software.source.server is defined
      - software.source.path is defined
      - software.dest.path is defined
