---
# ##############################################################
# This role will ensure SAP Hanan requirements are set on the OS
# ##############################################################

#- name: Enable Debugging
#  debug:
#    verbosity: "{{ debuglevel }}"

- include_tasks: ./assert.yml

- debug:
   msg: "######################     Stage 2 -  OS Config    ######################"

- include_tasks: ./saphana-check-media.yml
  tags:
    - hana-install
    - media-check

########################################################
# Loading OS specific tasks
########################################################
- include_tasks: "{{ './' + ansible_distribution + ansible_distribution_major_version + '/os-configuration.yml' }}"
  tags:
    - osprep
    - set-hostname
    - hana-install

- include_tasks: "{{ './' + ansible_distribution + ansible_distribution_major_version + '/os-tuning.yml' }}"
  tags:
    - osprep
    - system-tuning
    - hana-install

- include_tasks: "{{ './' + ansible_distribution + ansible_distribution_major_version + '/os-hardening.yml' }}"
  tags:
    - osprep
    - system-tuning
    - hana-install

