---
- name: " Stage 2.1 -   Check if folder is present"
  stat:
    path: "{{ hana_installdir }}"
  register: insdir

- name: " Stage 2.1 -   Copy installation folder from source"
  block:
    - file:
        path: "{{ hana_installdir }}"
        state: directory
      when: insdir.stat.isdir is not defined
    - synchronize:
        src: "{{ software.source.path }}"
        dest: "{{ software.dest.path }}"
      delegate_to: "{{ software.source.server }}"

- name: " Stage 2.1 -   Get HANA Version Information"
  shell:  awk ' ( $1 == "fullversion:" ) { print $2}'  "{{ hana_installdir }}"/DATA_UNITS/HDB_SERVER_LINUX_{{ ansible_architecture|upper }}/server/manifest
  changed_when: false
  register: hana_version

- name: " Stage 2.1 -   Make HANA Version persistent"
  set_fact: 
    hana_version: hana_version.stdout
